import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Button from '../components/Button/button.js';

const buttonConfigSmall = {
    clickHandler: () => console.log('click'),
    size: 'small',
    color: 'primary',
    label: 'Small'
};

const buttonConfigMedium = {
  clickHandler: () => console.log('click'),
  size: 'medium',
  color: 'primary',
  label: 'Medium'
}

const buttonConfigLarge = {
  clickHandler: () => console.log('click'),
  size: 'large',
  color: 'primary',
  label: 'Large'
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Text here</h1>
        <Button {...buttonConfigSmall}/>
        <Button {...buttonConfigMedium}/>
        <Button {...buttonConfigLarge}/>
      </main>
    </div>
  )
}
